week11/CourseManagement/config/routes.rb
Rails.application.routes.draw do
  resources :lectures do
    resources :tasks do
      resources :solutions
    end
  end

end

week11/CourseManagement/app/models/lecture.rb
class Lecture < ActiveRecord::Base
  has_many :tasks
end

week11/CourseManagement/app/models/solution.rb
class Solution < ActiveRecord::Base
  belongs_to :task
end

week11/CourseManagement/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :lecture
  has_many :solutions
end

week11/CourseManagement/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

week11/CourseManagement/app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all
  end

  def show
    @lecture = Lecture.find(params[:id]) 
  end
  
  def edit
    @lecture = Lecture.find(params[:id]) 
  end

  def new
    @lecture = Lecture.new    
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
      redirect_to lectures_path 
    else    
      render :new
    end
  end

  def update
    @lecture = Lecture.find(params[:id])
    if @lecture.update(lecture_params)
      redirect_to @lecture
    else
      render :edit
    end
  end

  def destroy
    @product = Lecture.find(params[:id])
    @product.destroy
    if @product.destroyed?
        redirect_to action: "index"
    else
        render @product.errors
    end  
  end

  private 
  def lecture_params
      params.require(:lecture).permit(:name, :text_body)
  end
end

week11/CourseManagement/app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_lecture

  def index
    @solutions = task.solutions  
  end

  def show
    @solution = task.solutions.find(params[:id])
  end

  def new
    @solution = Solution.new
  end

  def create
    # @task = @lecture.tasks.create(task_params)
    # solution_params.delete(task_id)
    @solution = task.solutions.create(solution_params)
    # @solution = @task.solutions.create(Solution.new(solution_params)) 
    # forgotten @
    if @solution.valid?(@solution)
      # forgotten _path
      redirect_to lecture_task_solutions_path(lecture, task)
    else  
      render :new, status: :unprocessable_entity
    end
  end

  
  private

  def task
    @task ||= Task.find(params[:task_id])
  end
  helper_method :task

  def lecture
    @lecture = Lecture.find(params[:lecture_id])
  end
  helper_method :task

  def solution_params
    # params.require(:task).permit(:name, :description)
    params.require(:solution).permit(:content)
  end
end

week11/CourseManagement/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_lecture

  def index
    @tasks = @lecture.tasks
  end

  def show
    @task = @lecture.tasks.find([:id])
  end

  def new
   @task = Task.new  
  end

  def edit
   @task = @lecture.tasks.find(params[:id])  
  end
  
  def update
    @task = @lecture.tasks.find(params[:id])
    @task.update(task_params)
     if @task.valid?(@task)
      redirect_to lecture_tasks_path(params[:lecture_id])
    else
      render :edit, status: :unprocessable_entity
    end
  end

  
  def create
    debugger
    @task = @lecture.tasks.create(task_params)
    if @task.valid?(@task)
      redirect_to lecture_tasks_path(params[:lecture_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_lecture
    @lecture = Lecture.find(params[:lecture_id])
  end
  
  def task_params
    params.require(:task).permit(:name, :description)
  end
end

week11/CourseManagement/app/helpers/application_helper.rb
module ApplicationHelper
end

week11/CourseManagement/app/helpers/lectures_helper.rb
module LecturesHelper
end

week11/CourseManagement/app/helpers/solutions_helper.rb
module SolutionsHelper
end

week11/CourseManagement/app/helpers/tasks_helper.rb
module TasksHelper
end

week11/CourseManagement/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CourseManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

week11/CourseManagement/app/views/solutions/_solution.html.erb
<%= f.label :content %> <%= f.text_field  :content %>
<%= f.submit "Submit" %>

week11/CourseManagement/app/views/solutions/index.html.erb
<% @solutions.each do |solution| %>
<p class="solution"> <%= solution.inspect %></p>
<% end %>
<%= link_to "Create", new_lecture_task_solution_path %>

week11/CourseManagement/app/views/solutions/new.html.erb
<h2>Add solution<h2/>

<%= form_for(@solution, url: lecture_task_solutions_path(lecture, task)) do |f| %>
  <%= render @solution, f: f %>
<% end %>



 

week11/CourseManagement/app/views/solutions/show.html.erb
<p id="notice"> <%= notice %> </p>
<%= form_for(@solution, url: lecture_task_solutions_path(lecture, task)) do |f| %>
<%= render @solution f: f %>
<% end %>

week11/CourseManagement/app/views/tasks/_task.html.erb
<%= f.label :name %> <%= f.text_field :name %>
<%= f.label :description %> <%= f.text_area :description %>

<%= f.submit "Submit" %>

week11/CourseManagement/app/views/tasks/edit.html.erb
<h2>Edit Task</h2>
<%= form_for(@task, url: lecture_tasks_path(@lecture)) do |f| %>
  <%= render @task, f: f %>
<% end %>

<br/>
<br/>


<!-- @task, method: :patch, url: lecture_task_path(@lecture, @task) -->

week11/CourseManagement/app/views/tasks/index.html.erb
<h2>Tasks</h2>

<% @tasks.each do |task| %>
  <p><%= link_to task.name, edit_lecture_task_path(@lecture, task) %></p>
<% end %>

<%= link_to "Add new task", new_lecture_task_path(@lecture), :style=>'color: green;' %>

week11/CourseManagement/app/views/tasks/new.html.erb
<h2>Create Task</h2>

<%= form_for(@task, url: lecture_tasks_path(@lecture)) do |f| %>
  <%= render @task, f: f %>
<% end %>

week11/CourseManagement/app/views/tasks/show.html.erb
<p>
<strong>name:</strong>
<%= @task.name %>
</p>

<p>
  <strong>Content</strong>
  <%= @task.description %>
</p>

<%= link_to "Submit solution", new_lecture_task_solution_path(@lecture, @task) %>


<%= link_to "View solutions", lecture_task_solutions_path(@lecture, @task) %>